sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t awscpukiller/docker-react -f Dockerfile.dev .

script:
  - docker run awscpukiller/docker-react npm run test -- --coverage
